[package]
name = "chonker7"
version = "7.42.0"
edition = "2021"

[dependencies]
# Core
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }

# Terminal UI - Pure crossterm, no ratatui!
crossterm = "0.28"

# PDF rendering
pdfium-render = { version = "0.8", features = ["thread_safe"] }
image = "0.25"

# Image display  
viuer = { version = "0.7.1", default-features = false, features = [] }  # Cross-terminal image display
image_0_24 = { package = "image", version = "0.24" }  # For viuer compatibility

# File watching
notify = "6.1"

# Fuzzy file finder (from Helix editor)
nucleo = "0.5"

# Clipboard support for EDIT mode
cli-clipboard = "0.4"

# Markdown rendering for MARKDOWN mode
termimad = "0.28"

# Sophisticated spatial text layout
rstar = "0.12"
euclid = "0.22"
grid = "0.14"
ordered-float = "4.2"

# Machine Learning (optional)
candle-core = { version = "0.9", optional = true }
candle-nn = { version = "0.9", optional = true }
candle-transformers = { version = "0.9", optional = true }
candle-metal-kernels = { version = "0.9", optional = true }
tokenizers = { version = "0.15", optional = true }
safetensors = { version = "0.4", optional = true }

# CoreML/ANE support (macOS only)
[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2", optional = true }
core-foundation = { version = "0.10", optional = true }

[features]
default = ["kitty-images"]
kitty-images = []

# ML features
ml = ["candle-core", "candle-nn", "candle-transformers", "tokenizers", "safetensors"]
coreml = ["ml", "objc", "core-foundation"]
metal = ["ml", "candle-metal-kernels"]